# Pandas

In [2]:
new_series = original_series.copy()

NameError: name 'original_series' is not defined

In [3]:
import pandas as pd 
series = pd.Series([1,2,3,4])
df = series.to_frame(name="Column1")

In [4]:
import pandas as pd 
import numpy as np 

# Sample Dataframe
df = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})

# Covert to NumPy array 
numpy_array = df.to_numpy()

In [5]:
import pandas as pd 
student_dict = {'Name':['Ankita','Vaishnavi','Harshad','Umesh'],'Age':[22,23,22,23],'Marks':[99,98,97,95]}

# create DataFrame from dict
df = pd.DataFrame(student_dict)
print(df)
print(df.iloc[[0,2]])

        Name  Age  Marks
0     Ankita   22     99
1  Vaishnavi   23     98
2    Harshad   22     97
3      Umesh   23     95
      Name  Age  Marks
0   Ankita   22     99
2  Harshad   22     97


In [6]:
import pandas as pd 
student_dict = {'Name':['Ankita','Vaishnavi','Harshad','Umesh'],'Age':[22,23,22,23],'Marks':[99,98,97,95]}

# create DataFrame from dict
df = pd.DataFrame(student_dict)
print(df)


print(df.iloc[[0,2]])

        Name  Age  Marks
0     Ankita   22     99
1  Vaishnavi   23     98
2    Harshad   22     97
3      Umesh   23     95
      Name  Age  Marks
0   Ankita   22     99
2  Harshad   22     97


In [7]:
import pandas as pd 
student_dict = {'Name':['Ankita','Vaishnavi','Harshad','Umesh'],'Age':[22,23,22,23],'Marks':[99,98,97,95]}

# create DataFrame from dict
df = pd.DataFrame(student_dict)
print(df)
print(df.loc[(df.Name=='Ankita')])

        Name  Age  Marks
0     Ankita   22     99
1  Vaishnavi   23     98
2    Harshad   22     97
3      Umesh   23     95
     Name  Age  Marks
0  Ankita   22     99


In [8]:
import pandas as pd 
student_dict = {'Name':['Ankita','Vaishanvi','Gayti'],'Age':[20,21,22],'Marks':[85,98,57]}
# Create DatFrame from dict
student_df=pd.DataFrame(student_dict)
print(student_df)

# Set index using column 
student_df=student_df.set_index('Name')
print(student_df)

student_df.reset_index(drop=True,inplace=True)
print(student_df)

        Name  Age  Marks
0     Ankita   20     85
1  Vaishanvi   21     98
2      Gayti   22     57
           Age  Marks
Name                 
Ankita      20     85
Vaishanvi   21     98
Gayti       22     57
   Age  Marks
0   20     85
1   21     98
2   22     57


# How to rename the index in a Pandas DataFrame

In [9]:
import pandas as pd 

student_dict = {'Name':['Ankita','Vaishanvi','Gayti'],'Age':[20,21,22],'Marks':[85,98,57]}
# Create DatFrame from dict
student_df=pd.DataFrame(student_dict)

# ser index using column
student_df = student_df.set_index('Name')
print(student_df)

student_df.index.names=['FirstName']
print(student_df)

           Age  Marks
Name                 
Ankita      20     85
Vaishanvi   21     98
Gayti       22     57
           Age  Marks
FirstName            
Ankita      20     85
Vaishanvi   21     98
Gayti       22     57


# How to get frequency count of unique items in a Pandas DataFrame?

In [10]:
# importing the moduk=le
import pandas as pd 

# creating the series
s = pd.Series(data=[1,2,3,4,3,5,2,7,1])

# displaying the series
print(s)

#finding the uniwye count prints(s.valu_counts())

0    1
1    2
2    3
3    4
4    3
5    5
6    2
7    7
8    1
dtype: int64


# How to delete a column in Pandas DataFrame

In [11]:
import pandas as pd 
student_dict = {'Name':['Ankita','Vaishanvi','Gayti'],'Age':[20,21,22],'Marks':[85,98,57]}

# Create DatFrame from dict
student_df = pd.DataFrame(student_dict)

# Set index using column
student_df = student_df.set_index('Name')
print(student_df)

student_df.drop('Age' ,axis=1,inplace=True)
print(student_df)


           Age  Marks
Name                 
Ankita      20     85
Vaishanvi   21     98
Gayti       22     57
           Marks
Name            
Ankita        85
Vaishanvi     98
Gayti         57


# How to delte a row in Pandas DataFrame?

In [12]:
import pandas as pd 
student_dict = {'Name':['Ankita','Vaishanvi','Gayti'],'Age':[20,21,22],'Marks':[85,98,57]}
# Create DatFrame from dict
student_df = pd.DataFrame(student_dict)

# set index using column
student_df = student_df.set_index('Name')
print(student_df)

student_df.drop(["Ankita"],inplace=True)
print(student_df)

           Age  Marks
Name                 
Ankita      20     85
Vaishanvi   21     98
Gayti       22     57
           Age  Marks
Name                 
Vaishanvi   21     98
Gayti       22     57


# How can we convert NumPy array ito a DataFrame?

In [13]:
# Python program to Create a 
# Pandas DataFrame from a Numpy
# array and specify the index
# column and column headers

# import required libraries 
import pandas as pd
import numpy as np 

# Creating a numpy array 
numpyArray = np.array([[115,222,343,],[323,242,356]])

# generating the Pandas Dataframe
#from the Numpy array and specifying
# name of index and columns 
dataframe = pd.DataFrame(data=numpyArray,index=["Row1","Row2"],columns=["Column1","Column2","Column3"])

#printing the dataframe
print(dataframe)

      Column1  Column2  Column3
Row1      115      222      343
Row2      323      242      356


# How do you split a DataFrame according to a booleand criterion?

In [14]:
import pandas as pd
student_dict = {'Name':['Ankita','Vaishanvi','Gayti'],'Age':[20,21,22],'Marks':[85,98,57]}
# Create DatFrame from dict
df = pd.DataFrame(student_dict)
print(df)

df1=df[df['Age']>10]
#printing df1
print(df1)

        Name  Age  Marks
0     Ankita   20     85
1  Vaishanvi   21     98
2      Gayti   22     57
        Name  Age  Marks
0     Ankita   20     85
1  Vaishanvi   21     98
2      Gayti   22     57


# How to create Timedelta objects in Pandas?

In [15]:
# importing neccessary libraries
import pandas as pd 
import numpy as np 

# Conversion from string format to data format takes place using 
print(pd.Timedelta('20 days 12 hours 45 minutes 3 seconds'))

20 days 12:45:03


In [16]:
# importing neccessary libraries 
import pandas as pd 
import numpy as np 

print(pd.Timedelta(16,unit='h'))# h here is used for hours

0 days 16:00:00


# Dataoffsets

In [17]:
import pandas as pd 
import numpy as np

print(pd.Timedelta(days=2,hours=16))

2 days 16:00:00


In [18]:
import pandas as pd
import numpy as np 

print(pd.Timedelta(days = 2, hours = 6,minutes = 23))

2 days 06:23:00


# How will you compute the percentile of a numerical series in Pandas?

In [19]:
import pandas as pd 
import numpy as np 

A = [random.randint(0,100)foriinrange(10)]
B = [random.randint(0,100)foriinrange(10)]

df = pd.DataFrame({'field_A':A,'field_B':B})

print(df.field_A.quantile(0.1)) # 10th oercentile

print(df.field_A.quantile(0.5)) # same as median

print(df.field_A.quantile(0.9)) # 90th percentile


SyntaxError: invalid syntax. Perhaps you forgot a comma? (812415224.py, line 4)

# How can we convert DataFrame into a Numpy array?

In [20]:
import pandas as pd 

# initalize a dataframe
df = pd.DataFrame([[10,12,33],[41,53,66],[17,81,19],[10,11,12]],columns=['X','Y','Z'])

#convert dataframe to numpy array 
arr = df.to_numpy()

print('\nNumpyArray\n--------\n',arr)
print(type(arr))



NumpyArray
--------
 [[10 12 33]
 [41 53 66]
 [17 81 19]
 [10 11 12]]
<class 'numpy.ndarray'>


# How to add a column to a Pandas DataFrame

In [29]:
# Add column
import pandas as pd 

student_dict={'Name':['Ankita','Vaishanvi','Gaytri'],'Age':[21,23,22],'Marks':[98,97,89]}

# create DataFrame from dict
student_df = pd.DataFrame(student_dict)
print(student_df)
address=['Dharashiv','Latur','Nagpur']
student_df['Address']=address

#Observe the result
print(student_df)
              

        Name  Age  Marks
0     Ankita   21     98
1  Vaishanvi   23     97
2     Gaytri   22     89
        Name  Age  Marks    Address
0     Ankita   21     98  Dharashiv
1  Vaishanvi   23     97      Latur
2     Gaytri   22     89     Nagpur


In [30]:
import pandas as pd 

student_dict={'Name':['Ankita','Vaishanvi','Gaytri'],'Age':[21,23,22],'Marks':[98,97,89]}

# create DataFrame from dict
student_df = pd.DataFrame(student_dict)
print(student_df)
address=['Dharashiv','Latur','Nagpur']
student_df.insert(2,"Address",['Dharashiv','Latur','Nagpur'],True)

# Observe the result 
print(student_df)

        Name  Age  Marks
0     Ankita   21     98
1  Vaishanvi   23     97
2     Gaytri   22     89
        Name  Age    Address  Marks
0     Ankita   21  Dharashiv     98
1  Vaishanvi   23      Latur     97
2     Gaytri   22     Nagpur     89


In [31]:
import pandas as pd 
student_dict={'Name':['Ankita','Vaishanvi','Gaytri'],'Age':[21,23,22],'Marks':[98,97,89]}

# create DataFrame From dict 
student_df = pd.DataFrame(student_dict)
print(student_df)
df2 = student_df.assign(address=['Dharashiv','Latur','Nagpur'])

# Observe the result 
print(df2)

        Name  Age  Marks
0     Ankita   21     98
1  Vaishanvi   23     97
2     Gaytri   22     89
        Name  Age  Marks    address
0     Ankita   21     98  Dharashiv
1  Vaishanvi   23     97      Latur
2     Gaytri   22     89     Nagpur


In [37]:
import pandas as pd 
student_dict={'Name':['Ankita','Vaishanvi','Gaytri'],'Age':[21,23,22],'Marks':[98,97,89]}

# Create DatFrame from dict 
studenr_df=pd.DataFrame(student_dict)
print(student_df)

address={'Dharashiv':'Ankita','Latur':'Vaishanvi','Nagpur':'Gaytri'}
student_df['Addres']=address

# Observe the output
print(student_df)

        Name  Age  Marks
0     Ankita   21     98
1  Vaishanvi   23     97
2     Gaytri   22     89
3       Alex   19     93
        Name  Age  Marks Addres
0     Ankita   21     98    NaN
1  Vaishanvi   23     97    NaN
2     Gaytri   22     89    NaN
3       Alex   19     93    NaN


# How to add a row to a Pandas DataFrame?

In [38]:
import pandas as pd 
student_dict={'Name':['Ankita','Vaishanvi','Gaytri'],'Age':[21,23,22],'Marks':[98,97,89]}

# Create DataFrame from dict
student_df=pd.DataFrame(student_dict)
print(student_df)
student_df.loc[len(student_df.index)]=['Alex',19,93]
print(student_df)

        Name  Age  Marks
0     Ankita   21     98
1  Vaishanvi   23     97
2     Gaytri   22     89
        Name  Age  Marks
0     Ankita   21     98
1  Vaishanvi   23     97
2     Gaytri   22     89
3       Alex   19     93


In [39]:
import pandas as pd 

df2 = {'Name':'Tom','Age':18,'Marks':90}
student_df=student_df.append(df2.ignore_index=True)
print(student_df)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (4056755344.py, line 4)

In [41]:
import pandas as pd 
student_dict={'Name':['Ankita','Vaishanvi','Gaytri'],'Age':[21,23,22],'Marks':[98,97,89]}

# create DataFrame from dict
df=pd.DataFrame(student_dict)
print(df)

dict={'Name':['Vivek','Vikram'],'Age':[19,12],'Marks':[98,87]}

df2 = pd.DataFrame(dict)
print(df2)

df3 = pd.concat([df2,df2],ignore_index=True)
print(df3)

        Name  Age  Marks
0     Ankita   21     98
1  Vaishanvi   23     97
2     Gaytri   22     89
     Name  Age  Marks
0   Vivek   19     98
1  Vikram   12     87
     Name  Age  Marks
0   Vivek   19     98
1  Vikram   12     87
2   Vivek   19     98
3  Vikram   12     87


# How to set Index to a Pandas DataFrame?

In [43]:
import pandas as pd 

student_dict={'Name':['Ankita','Vaishanvi','Gaytri'],'Age':[21,23,22],'Marks':[98,97,89]}

# Create DataFrame from dict 
student_df = pd.DataFrame(student_dict)
print(student_df)

# set index using column 
student_df = student_df.set_index('Name')
print(student_df)

        Name  Age  Marks
0     Ankita   21     98
1  Vaishanvi   23     97
2     Gaytri   22     89
           Age  Marks
Name                 
Ankita      21     98
Vaishanvi   23     97
Gaytri      22     89


In [46]:
import pandas as pd 

student_dict={'Name':['Ankita','Vaishanvi','Gaytri'],'Age':[21,23,22],'Marks':[98,97,89]}

# Create DataFrame from dict 
student_df = pd.DataFrame(student_dict)
print(student_df)

# set index using column
student_df = student_df.set_index(['Name','Marks'])
print(student_df)

        Name  Age  Marks
0     Ankita   21     98
1  Vaishanvi   23     97
2     Gaytri   22     89
                 Age
Name      Marks     
Ankita    98      21
Vaishanvi 97      23
Gaytri    89      22


In [47]:
index = pd.Index(['x1','x2','x3'])
student_df = student_df.set_index(index)
print(student_df)

    Age
x1   21
x2   23
x3   22


In [49]:
import pandas as pd 
student_dict={'Name':['Ankita','Vaishanvi','Gaytri'],'Age':[21,23,22],'Marks':[98,97,89]}

# Create DataFrame from dict 
student_df=pd.DataFrame(student_dict)
print(student_df)

index = pd.Index(['x1','x2','x3'])
student_df=student_df.set_index([index,'Name'])
print(student_df)

        Name  Age  Marks
0     Ankita   21     98
1  Vaishanvi   23     97
2     Gaytri   22     89
              Age  Marks
   Name                 
x1 Ankita      21     98
x2 Vaishanvi   23     97
x3 Gaytri      22     89
