# Numpy 

In [11]:
import numpy as np

In [12]:
np.__version__

'2.3.5'

In [13]:
import sys 
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

# Creating Arrays

In [14]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [15]:
type(my_list)

list

In [16]:
arr = np.array(my_list)

In [17]:
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
type(arr)

numpy.ndarray

In [19]:
type(my_list)

list

In [20]:
np. # we learn important function 

SyntaxError: invalid syntax (1655120754.py, line 1)

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(3.0)

array([0., 1., 2.])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
np.arange(20,10)

array([], dtype=int64)

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [29]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [30]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [31]:
np.arange(30,20)

array([], dtype=int64)

In [32]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [33]:
np.arange(10,10)

array([], dtype=int64)

In [34]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,30,5) # -10 starting from 30- end point 5- step count 

In [ ]:
np.arange(0,10,3)

In [35]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [36]:
np.zeros(3) # parameter tunning

array([0., 0., 0.])

In [37]:
np.zeros(5, dtype=int) # parameter tunning

array([0, 0, 0, 0, 0])

In [38]:
np.zeros((2,2),dtype = int) 

array([[0, 0],
       [0, 0]])

In [39]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [40]:
zero = np.zeros([2,2])
print(zero)

print('###')
print(type(zero))

[[0. 0.]
 [0. 0.]]
###
<class 'numpy.ndarray'>


In [41]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [45]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [48]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [49]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [50]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [51]:
np.zeros((5,10)) # bydefault large -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunning 

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [53]:
print(np.zeros(n,dtype=int)) # hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [54]:
n

(6, 7)

In [55]:
n1

(6, 8)

In [56]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [57]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [59]:
np.ones(3)

array([1., 1., 1.])

In [60]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [61]:
np.ones(4)

array([1., 1., 1., 1.])

In [62]:
n

(6, 7)

In [63]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [64]:
np.ones((5,4),dtype=int) # by default 5 - rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [65]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [66]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [67]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [68]:
np.ones(2)

array([1., 1.])

In [69]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [71]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [72]:
range(5)

range(0, 5)

In [73]:
r = range(5)
r

range(0, 5)

In [74]:
for i in r:
    print(i)
    

0
1
2
3
4


In [75]:
list(range(5))

[0, 1, 2, 3, 4]

In [76]:
range(1,10)

range(1, 10)

In [77]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [78]:
list(range(1,10,3))

[1, 4, 7]

In [79]:
y = list(range(12))

In [80]:
rand(3,2)

NameError: name 'rand' is not defined

In [81]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [82]:
np.random.rand(5)

array([0.35351052, 0.22611388, 0.53037309, 0.84924168, 0.42024046])

In [83]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [84]:
np.random.rand(2,4)

array([[0.54658592, 0.55484785, 0.5461031 , 0.05570094],
       [0.72723477, 0.44549153, 0.03187425, 0.70985392]])

In [85]:
np.random.randint(2,4)

2

In [86]:
np.random.randint(2,20) # 2nd argument is exclusive

13

In [87]:
np.random.randint(0,1)

0

In [88]:
np.random.randint(10,20,5)

array([11, 11, 12, 12, 15], dtype=int32)

In [89]:
np.random.randint(1,6,4)

array([2, 1, 4, 3], dtype=int32)

In [90]:
np.random.rand(3)

array([0.71140009, 0.76531488, 0.09345875])

In [91]:
np.random.randint(1)

0

In [92]:
np.random.randint(30,20,10)

ValueError: low >= high

In [93]:
np.random.randint(-30,20,10)

array([-11,  10,   5,  18, -15,   9,   5,  -9,   8, -21], dtype=int32)

In [94]:
np.random.randint(20,30,10)

array([21, 21, 26, 28, 28, 24, 20, 22, 24, 27], dtype=int32)

In [95]:
np.random.randint(5,9) # Get the value <=1 & >=5

8

In [96]:
np.random.randint(10,21,3)

array([17, 12, 13], dtype=int32)

In [97]:
np.random.randint(1,12,10)

array([10,  8,  7,  3,  8,  5,  8, 10,  3,  4], dtype=int32)

In [98]:
np.random.randint(10,40,(10,10)) # generate the element 10 - 30 with 4*4 mtri 

array([[31, 12, 19, 26, 34, 19, 34, 31, 30, 36],
       [22, 17, 28, 14, 29, 24, 20, 21, 12, 29],
       [25, 23, 30, 22, 37, 22, 35, 35, 26, 30],
       [16, 36, 29, 33, 25, 24, 34, 31, 27, 27],
       [33, 11, 15, 35, 15, 39, 30, 20, 20, 32],
       [30, 35, 28, 19, 36, 38, 13, 38, 13, 18],
       [36, 17, 35, 21, 30, 21, 34, 39, 11, 24],
       [30, 26, 35, 23, 27, 37, 22, 16, 14, 20],
       [32, 32, 28, 11, 30, 27, 33, 10, 29, 13],
       [29, 30, 31, 36, 10, 36, 21, 32, 22, 14]], dtype=int32)

In [99]:
np.random.randint(1,100,(12,10)) # generate the element 10 - 30 with 4*4 mtri

array([[26, 41, 62, 51, 31, 45, 11, 53, 55, 26],
       [56, 49, 55, 15, 70, 58, 32, 94, 53, 27],
       [57, 31, 43, 37, 54, 51, 16, 37, 80, 90],
       [82,  9, 67, 71, 60,  3, 86, 68, 34, 54],
       [64, 32, 87, 16, 95, 59, 36, 93, 35, 79],
       [78, 65, 66, 45, 72, 96, 41, 48, 71, 82],
       [30,  5, 19,  5, 63, 94, 17, 70, 53, 31],
       [61, 62, 52, 60, 63, 21, 59, 12, 80, 50],
       [78, 55, 92, 47, 66, 36, 39, 79, 70, 38],
       [17, 32, 43, 30, 36, 16, 68, 17, 13, 26],
       [42, 97, 51, 19, 63, 19, 52, 75,  6, 88],
       [61, 53, 80, 75, 51, 70, 26, 96, 67, 60]], dtype=int32)

In [100]:
np.random.rand(4)

array([0.50668405, 0.39391805, 0.19611838, 0.36362863])

In [101]:
np.random.rand(4,5)

array([[0.4421821 , 0.90763476, 0.31982026, 0.86686623, 0.7768899 ],
       [0.09468   , 0.1601358 , 0.53671309, 0.22697863, 0.13653716],
       [0.15945923, 0.11412878, 0.05359091, 0.43448022, 0.30179562],
       [0.9399401 , 0.90558609, 0.56562061, 0.77426634, 0.16004199]])

In [102]:
np.random.randint(3)

0

In [103]:
np.random.randint(10,15)

13

In [104]:
np.random.randint(1,5,3)

array([2, 3, 1], dtype=int32)

In [105]:
np.random.randint(1,5,4)

array([1, 1, 3, 4], dtype=int32)

In [106]:
np.random.randint(1,5,2)

array([2, 2], dtype=int32)

In [107]:
np.random.randint(5,2,3)

ValueError: low >= high

In [108]:
np.random.randint(-5,2,3)

array([-4, -3, -5], dtype=int32)

In [109]:
np.random.randint(10,40,(10,10))

array([[37, 13, 24, 37, 18, 19, 31, 39, 36, 30],
       [16, 29, 21, 14, 38, 18, 23, 16, 31, 28],
       [37, 27, 14, 27, 33, 37, 20, 23, 29, 13],
       [32, 32, 37, 34, 15, 39, 29, 20, 37, 21],
       [12, 12, 19, 28, 33, 20, 30, 27, 37, 13],
       [37, 24, 22, 12, 17, 25, 34, 15, 18, 15],
       [16, 10, 12, 39, 19, 24, 21, 36, 32, 35],
       [24, 22, 20, 18, 30, 11, 29, 22, 31, 25],
       [28, 34, 34, 21, 18, 33, 29, 23, 14, 34],
       [12, 23, 34, 39, 32, 20, 15, 32, 15, 33]], dtype=int32)

In [110]:
ri = np.random.randint(10,40,(10,10))
ri

array([[14, 10, 25, 15, 11, 23, 32, 32, 25, 20],
       [36, 34, 23, 26, 15, 22, 14, 34, 27, 17],
       [14, 34, 22, 16, 13, 34, 32, 22, 37, 32],
       [26, 21, 33, 39, 25, 38, 27, 13, 33, 28],
       [38, 37, 20, 11, 21, 32, 19, 28, 36, 25],
       [25, 16, 14, 11, 25, 37, 36, 20, 36, 28],
       [17, 37, 11, 17, 21, 29, 24, 13, 39, 25],
       [25, 38, 36, 32, 11, 25, 13, 20, 21, 19],
       [25, 25, 32, 36, 23, 32, 21, 25, 22, 26],
       [22, 11, 34, 26, 12, 19, 10, 11, 31, 29]], dtype=int32)

In [111]:
len(ri) # It will print by default

10

In [112]:
ri = np.random.randint(10,40,(3,5))
ri

array([[20, 13, 32, 10, 11],
       [37, 24, 37, 16, 25],
       [26, 18, 38, 39, 24]], dtype=int32)

In [113]:
len(ri)

3

In [114]:
ri.shape # gives a rows and columns

(3, 5)

In [115]:
id(ri)

2198278300912

In [116]:
ri

array([[20, 13, 32, 10, 11],
       [37, 24, 37, 16, 25],
       [26, 18, 38, 39, 24]], dtype=int32)

# Slicing in Numpy 

In [117]:
ri[:]

array([[20, 13, 32, 10, 11],
       [37, 24, 37, 16, 25],
       [26, 18, 38, 39, 24]], dtype=int32)

In [118]:
ri[1]

array([37, 24, 37, 16, 25], dtype=int32)

In [119]:
ri

array([[20, 13, 32, 10, 11],
       [37, 24, 37, 16, 25],
       [26, 18, 38, 39, 24]], dtype=int32)

In [120]:
ri[0:3]

array([[20, 13, 32, 10, 11],
       [37, 24, 37, 16, 25],
       [26, 18, 38, 39, 24]], dtype=int32)

In [121]:
ri_1 = np.random.randint(10,40,(10,10))
print(ri_1)

[[28 33 38 30 39 17 39 37 11 32]
 [29 34 13 26 18 13 21 38 23 14]
 [39 32 29 21 30 33 28 33 16 17]
 [17 34 34 12 23 34 10 36 17 35]
 [24 37 21 12 13 39 27 26 35 20]
 [10 26 30 33 32 18 37 17 14 18]
 [21 26 26 31 30 35 13 30 11 21]
 [16 35 23 26 23 30 12 21 24 15]
 [34 23 22 32 31 37 37 27 38 24]
 [21 32 21 14 17 15 12 25 25 19]]


In [122]:
ri_1 = np.random.randint(10,40,(10,10))
(ri_1)

array([[27, 29, 21, 39, 23, 24, 33, 13, 26, 12],
       [22, 24, 29, 13, 35, 33, 28, 35, 36, 35],
       [32, 24, 33, 15, 34, 22, 17, 23, 17, 33],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32],
       [36, 32, 12, 14, 28, 37, 22, 17, 20, 14],
       [38, 19, 27, 25, 36, 12, 12, 17, 35, 23]], dtype=int32)

In [123]:
ri_1.shape

(10, 10)

In [124]:
ri_1

array([[27, 29, 21, 39, 23, 24, 33, 13, 26, 12],
       [22, 24, 29, 13, 35, 33, 28, 35, 36, 35],
       [32, 24, 33, 15, 34, 22, 17, 23, 17, 33],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32],
       [36, 32, 12, 14, 28, 37, 22, 17, 20, 14],
       [38, 19, 27, 25, 36, 12, 12, 17, 35, 23]], dtype=int32)

In [125]:
ri_1[:]

array([[27, 29, 21, 39, 23, 24, 33, 13, 26, 12],
       [22, 24, 29, 13, 35, 33, 28, 35, 36, 35],
       [32, 24, 33, 15, 34, 22, 17, 23, 17, 33],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32],
       [36, 32, 12, 14, 28, 37, 22, 17, 20, 14],
       [38, 19, 27, 25, 36, 12, 12, 17, 35, 23]], dtype=int32)

In [126]:
ri_1[3:8]

array([[10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32]], dtype=int32)

In [127]:
ri_1[3,8]

np.int32(26)

In [128]:
print(ri_1[3,8])

26


In [129]:
ri_1[-5]

array([15, 28, 21, 24, 30, 17, 12, 35, 14, 25], dtype=int32)

In [130]:
ri_1[-5,3]

np.int32(24)

In [131]:
print(ri_1[-5,3])

24


In [132]:
ri_1

array([[27, 29, 21, 39, 23, 24, 33, 13, 26, 12],
       [22, 24, 29, 13, 35, 33, 28, 35, 36, 35],
       [32, 24, 33, 15, 34, 22, 17, 23, 17, 33],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32],
       [36, 32, 12, 14, 28, 37, 22, 17, 20, 14],
       [38, 19, 27, 25, 36, 12, 12, 17, 35, 23]], dtype=int32)

In [133]:
ri_1[::3]

array([[27, 29, 21, 39, 23, 24, 33, 13, 26, 12],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [38, 19, 27, 25, 36, 12, 12, 17, 35, 23]], dtype=int32)

In [134]:
ri_1

array([[27, 29, 21, 39, 23, 24, 33, 13, 26, 12],
       [22, 24, 29, 13, 35, 33, 28, 35, 36, 35],
       [32, 24, 33, 15, 34, 22, 17, 23, 17, 33],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32],
       [36, 32, 12, 14, 28, 37, 22, 17, 20, 14],
       [38, 19, 27, 25, 36, 12, 12, 17, 35, 23]], dtype=int32)

In [135]:
ri_1[::-1]

array([[38, 19, 27, 25, 36, 12, 12, 17, 35, 23],
       [36, 32, 12, 14, 28, 37, 22, 17, 20, 14],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 24, 33, 15, 34, 22, 17, 23, 17, 33],
       [22, 24, 29, 13, 35, 33, 28, 35, 36, 35],
       [27, 29, 21, 39, 23, 24, 33, 13, 26, 12]], dtype=int32)

In [136]:
ri_1[::-5]

array([[38, 19, 27, 25, 36, 12, 12, 17, 35, 23],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28]], dtype=int32)

In [137]:
ri_1[2]

array([32, 24, 33, 15, 34, 22, 17, 23, 17, 33], dtype=int32)

In [138]:
ri_1[:,2]

array([21, 29, 33, 13, 37, 21, 17, 30, 12, 27], dtype=int32)

In [139]:
ri_1

array([[27, 29, 21, 39, 23, 24, 33, 13, 26, 12],
       [22, 24, 29, 13, 35, 33, 28, 35, 36, 35],
       [32, 24, 33, 15, 34, 22, 17, 23, 17, 33],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32],
       [36, 32, 12, 14, 28, 37, 22, 17, 20, 14],
       [38, 19, 27, 25, 36, 12, 12, 17, 35, 23]], dtype=int32)

In [140]:
print(ri_1[2])
print(ri_1[:,2])

[32 24 33 15 34 22 17 23 17 33]
[21 29 33 13 37 21 17 30 12 27]


In [141]:
ri_1

array([[27, 29, 21, 39, 23, 24, 33, 13, 26, 12],
       [22, 24, 29, 13, 35, 33, 28, 35, 36, 35],
       [32, 24, 33, 15, 34, 22, 17, 23, 17, 33],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32],
       [36, 32, 12, 14, 28, 37, 22, 17, 20, 14],
       [38, 19, 27, 25, 36, 12, 12, 17, 35, 23]], dtype=int32)

In [142]:
ri_1[:,8]

array([26, 36, 17, 26, 34, 14, 32, 38, 20, 35], dtype=int32)

In [143]:
ri_1[:,-8]

array([21, 29, 33, 13, 37, 21, 17, 30, 12, 27], dtype=int32)

In [144]:
ri_1

array([[27, 29, 21, 39, 23, 24, 33, 13, 26, 12],
       [22, 24, 29, 13, 35, 33, 28, 35, 36, 35],
       [32, 24, 33, 15, 34, 22, 17, 23, 17, 33],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32],
       [36, 32, 12, 14, 28, 37, 22, 17, 20, 14],
       [38, 19, 27, 25, 36, 12, 12, 17, 35, 23]], dtype=int32)

In [145]:
ri_1[2:6,5:8]

array([[22, 17, 23],
       [10, 27, 38],
       [23, 19, 12],
       [17, 12, 35]], dtype=int32)

In [146]:
ri_1

array([[27, 29, 21, 39, 23, 24, 33, 13, 26, 12],
       [22, 24, 29, 13, 35, 33, 28, 35, 36, 35],
       [32, 24, 33, 15, 34, 22, 17, 23, 17, 33],
       [10, 13, 13, 31, 25, 10, 27, 38, 26, 18],
       [32, 34, 37, 39, 16, 23, 19, 12, 34, 28],
       [15, 28, 21, 24, 30, 17, 12, 35, 14, 25],
       [19, 32, 17, 18, 30, 16, 14, 39, 32, 35],
       [24, 17, 30, 12, 23, 10, 37, 15, 38, 32],
       [36, 32, 12, 14, 28, 37, 22, 17, 20, 14],
       [38, 19, 27, 25, 36, 12, 12, 17, 35, 23]], dtype=int32)

In [147]:
ri_1[0:3,0:3]

array([[27, 29, 21],
       [22, 24, 29],
       [32, 24, 33]], dtype=int32)

In [148]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [149]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [150]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [151]:
np.arange(1,13).reshape(2,3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [152]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [153]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# Operations 

In [154]:
a = np.random.randint(10,20,10)
a

array([19, 15, 14, 12, 11, 17, 16, 11, 17, 19], dtype=int32)

In [155]:
id(a)

2198278818384

In [156]:
arr

array([0, 1, 2, 3, 4, 5])

In [160]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [24, 33,  3, 10, 41, 80, 49, 57, 11, 49],
       [ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53]], dtype=int32)

In [161]:
arr 

array([0, 1, 2, 3, 4, 5])

In [162]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [163]:
arr

array([0, 1, 2, 3, 4, 5])

In [164]:
arr[:4]

array([0, 1, 2, 3])

In [165]:
arr2[:]

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [24, 33,  3, 10, 41, 80, 49, 57, 11, 49],
       [ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53]], dtype=int32)

In [166]:
arr2[0:5]

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82]], dtype=int32)

In [167]:
arr2

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [24, 33,  3, 10, 41, 80, 49, 57, 11, 49],
       [ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53]], dtype=int32)

In [168]:
arr2[1,4]

np.int32(44)

In [169]:
arr2

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [24, 33,  3, 10, 41, 80, 49, 57, 11, 49],
       [ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53]], dtype=int32)

In [170]:
arr2[-5,5]

np.int32(12)

In [171]:
arr2[-5,-5]

np.int32(12)

In [172]:
arr2

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [24, 33,  3, 10, 41, 80, 49, 57, 11, 49],
       [ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53]], dtype=int32)

In [173]:
arr2[-1,-2]

np.int32(94)

In [174]:
arr2

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [24, 33,  3, 10, 41, 80, 49, 57, 11, 49],
       [ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53]], dtype=int32)

In [175]:
arr2[::-1]

array([[ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53],
       [24, 33,  3, 10, 41, 80, 49, 57, 11, 49],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [30, 68, 54, 72, 32, 73, 34, 90, 53, 19]], dtype=int32)

In [176]:
arr2

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [24, 33,  3, 10, 41, 80, 49, 57, 11, 49],
       [ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53]], dtype=int32)

In [177]:
arr2[::-2]

array([[ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12]], dtype=int32)

In [178]:
arr2

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [24, 33,  3, 10, 41, 80, 49, 57, 11, 49],
       [ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53]], dtype=int32)

In [179]:
arr2[::-3]

array([[ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [30, 68, 54, 72, 32, 73, 34, 90, 53, 19]], dtype=int32)

In [180]:
arr2

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70],
       [29, 37, 92, 39,  0, 29, 32, 24, 24, 53],
       [24, 33,  3, 10, 41, 80, 49, 57, 11, 49],
       [ 0, 44,  4, 82,  1, 71, 51, 18, 94, 53]], dtype=int32)

In [181]:
arr2[:-3]

array([[30, 68, 54, 72, 32, 73, 34, 90, 53, 19],
       [73, 80, 93, 70, 44, 92, 54, 83, 24, 12],
       [27, 20, 51, 64, 78, 93, 22, 66, 30, 47],
       [22, 79, 56,  5, 57, 15, 87, 21, 78, 23],
       [14,  2, 79, 99, 11, 48, 86, 11, 87, 82],
       [42, 90, 41, 88, 22, 12, 21, 38, 38, 22],
       [70,  2, 38, 38, 44, 94, 69, 93, 68, 70]], dtype=int32)

In [182]:
arr

array([0, 1, 2, 3, 4, 5])

In [183]:
arr.max()

np.int64(5)

In [184]:
arr.min()

np.int64(0)

In [185]:
arr

array([0, 1, 2, 3, 4, 5])

In [186]:
arr.mean()

np.float64(2.5)

In [187]:
arr

array([0, 1, 2, 3, 4, 5])

In [188]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [190]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# Without work on import* can you please find the median , mode )

In [191]:
arr

array([0, 1, 2, 3, 4, 5])

In [192]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [193]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [194]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [195]:
arr

array([0, 1, 2, 3, 4, 5])

In [196]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [197]:
arr 

array([0, 1, 2, 3, 4, 5])

In [198]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [199]:
arr.reshape(2,3,order='F') # Print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [200]:
arr.reshape(2,3,order='A') # A almost give you c type output

array([[0, 1, 2],
       [3, 4, 5]])

In [201]:
arr 

array([0, 1, 2, 3, 4, 5])

In [202]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [203]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [204]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [205]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [206]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [207]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [208]:
arr

array([0, 1, 2, 3, 4, 5])

In [209]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing 

In [210]:
mat = np.arange(0,100).reshape(10,10)

In [211]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
row = 4 
col = 5

col

5

In [213]:
row

4

In [214]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [215]:
mat[row,col]

np.int64(45)

In [216]:
mat[4,5]

np.int64(45)

In [217]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [219]:
col = 6

In [220]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat[6] # default it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [222]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [223]:
# with Slices 
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [224]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [225]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [226]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [227]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [228]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [229]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [230]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [231]:
row

4

In [232]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [233]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [234]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [235]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [236]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [237]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [238]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [240]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [241]:
row

4

In [242]:
col

6

In [243]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [244]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [245]:
mat[1,4]

np.int64(14)

In [246]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [247]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [248]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [250]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [251]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [252]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [253]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [254]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [255]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [256]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [257]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [258]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [259]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [260]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [261]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [262]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [263]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [264]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [265]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [266]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [267]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [268]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [269]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [270]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [271]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [272]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [273]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [274]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [275]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [276]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [277]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [278]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicated only column parts 

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [279]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [280]:
mat[0,1]

np.int64(1)

In [281]:
mat[1,6]

np.int64(16)

In [282]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [283]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [284]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [285]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [286]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [287]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [288]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [289]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [290]:
mat[3,5]

np.int64(35)

In [291]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [292]:
mat[1:2,2:4]

array([[12, 13]])

In [293]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [294]:
mat[2:3,2:3]

array([[22]])

In [295]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [296]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [297]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [298]:
mat[2:3,4:5]

array([[24]])

# Masking 

In [299]:
mat # we also called as filter 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [300]:
id(mat)

2198281274640

In [301]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [302]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [303]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [304]:
mat > 50 

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [305]:
mat[mat==50]

array([50])

In [306]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [307]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [308]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [309]:
a1 = mat[mat<50]

In [310]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [311]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [312]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [313]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [314]:
a4 = mat[mat==50]
a4

array([50])

# Python Program to Generate OTP 

In [321]:
import random 

def generate_otp(length=4):
     """Generate a numeric OTP of a specified length."""
     digits = '012345'
     otp = ''.join(random.choice(digits)for _ in range(length))
     return otp

# Example usage
otp_length = 4 # you can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is:{otp}")


Your OTP is:3322


In [322]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()
    

good even
good even
good even


In [323]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [326]:
list=['a','b','c',1,5]
print(list.pop)

<built-in method pop of list object at 0x000001FFD3847D00>


In [327]:
x = [1,2,3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
